language: python
python:
- 3.10
- 3.9
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Tobi-De
  password:
    secure: jI+2gAuGcXw8vF78cmc0HfKQDM6UOjNnDcJk/V5G0Y5khcDcL4XY4nVSQV1ZoSqA4lRBZ/wOPEcK2aux9JgrpD+PL0RNgHW2+jPibAzXsaJ8yGc2rzsHCX677io7KZyWALAMgPSJwY2UFvc8a6Ysd/V+lWtI+7UnnAA7O/Wt7wQzefgeJmx71D1VyTVaT7B2ZZIebRXJu/2fUQYhAXpXvHjJPz/5FCfrJp1KcN2sPXyLYuFL4ZFvQMOSXOF0qomVjq6dMpqRZvVdNadzAuROtGHWjQ7yL9yH//UWq4qBvibeBbcsGsDIhg+XZz+gtBNmb0NsQpe5k7l9g8N5BWhuQY8jm+7OSOCsFZb017aAnXRdHDesWpq2D8KdfCXsax8zGzVmd5F8wm+ySvVY42YGQKhk1ES2r1Cq/VLbaStPTidJxWzoXeJiLYF9XAUWUjESj6pUbnFhTFV+Bocx30g8hS6CBxoNUQ+lTEvHTTTcr4b8EUblqyvOnkNVXV5aEoXDXjTaS8jQzr+TxtfATlUaTaZ0d2BthMqOupTJq8TKWPlmJt7n4845Cqn4lUhwPger9L7DC0xuXIhwBJDrBzv+VT2vC6YutF6ZxGB0UA7S5FXBRGoPtjBvPkTJ/uitt5d6TnB+/GSLxrVszJi/+QJjlxGprufgV5ZfzdEcg/I1lG4=
  on:
    tags: true
    repo: Tobi-De/qosic-sdk
    python: 3.8
